# Generated by Django 3.1.4 on 2020-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feemaster',
            name='Fee Structure already exist',
        ),
        migrations.AddConstraint(
            model_name='feemaster',
            constraint=models.UniqueConstraint(fields=('course', 'category', 'feehead', 'gender', 'board'), name='Fee Structure already exist'),
        ),
    ]
