# Generated by Django 3.1.4 on 2020-12-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201223_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='merit',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Merit1'), (2, 'Merit2'), (3, 'Merit3')], null=True),
        ),
    ]
