# Generated by Django 3.1.4 on 2020-12-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstatus',
            old_name='easypayid',
            new_name='easepayid',
        ),
    ]
