# Generated by Django 3.1.4 on 2020-12-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201223_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clc_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CLCStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm_roll', models.PositiveIntegerField(verbose_name='Exam Roll. No.')),
                ('cls_roll', models.PositiveIntegerField(verbose_name='Class Roll. No.')),
                ('session', models.CharField(choices=[('2020-2021', '2020-2021'), ('2019-2020', '2019-2020'), ('2018-2019', '2018-2019'), ('2017-2018', '2017-2018'), ('2016-2017', '2016-2017'), ('2015-2016', '2015-2016'), ('2014-2015', '2014-2015'), ('2013-2014', '2013-2014'), ('2012-2013', '2012-2013'), ('2011-2012', '2011-2012'), ('2010-2011', '2010-2011'), ('2009-2010', '2009-2010'), ('2008-2009', '2008-2009'), ('2007-2008', '2007-2008'), ('2006-2007', '2006-2007'), ('2005-2006', '2005-2006'), ('2004-2005', '2004-2005'), ('2003-2004', '2003-2004'), ('2002-2003', '2002-2003'), ('2001-2002', '2001-2002'), ('2000-2001', '2000-2001'), ('1999-2000', '1999-2000'), ('1998-1999', '1998-1999'), ('1997-1998', '1997-1998'), ('1996-1997', '1996-1997'), ('1995-1996', '1995-1996'), ('1994-1995', '1994-1995'), ('1993-1994', '1993-1994'), ('1992-1993', '1992-1993'), ('1991-1992', '1991-1992'), ('1990-1991', '1990-1991'), ('1989-1990', '1989-1990'), ('1988-1989', '1988-1989'), ('1987-1988', '1987-1988'), ('1986-1987', '1986-1987'), ('1985-1986', '1985-1986')], max_length=9)),
                ('exm_year', models.PositiveIntegerField(choices=[(20, 2020), (19, 2019), (18, 2018), (17, 2017), (16, 2016), (15, 2015), (14, 2014), (13, 2013), (12, 2012), (11, 2011), (10, 2010), (9, 2009), (8, 2008), (7, 2007), (6, 2006), (5, 2005), (4, 2004), (3, 2003), (2, 2002), (1, 2001), (0, 2000), (99, 1999), (98, 1998), (97, 1997), (96, 1996), (95, 1995), (94, 1994), (93, 1993), (92, 1992), (91, 1991), (90, 1990), (89, 1989), (88, 1988), (87, 1987), (86, 1986), (85, 1985)], verbose_name='Examination Year')),
                ('pass_year', models.PositiveIntegerField(choices=[(20, 2020), (19, 2019), (18, 2018), (17, 2017), (16, 2016), (15, 2015), (14, 2014), (13, 2013), (12, 2012), (11, 2011), (10, 2010), (9, 2009), (8, 2008), (7, 2007), (6, 2006), (5, 2005), (4, 2004), (3, 2003), (2, 2002), (1, 2001), (0, 2000), (99, 1999), (98, 1998), (97, 1997), (96, 1996), (95, 1995), (94, 1994), (93, 1993), (92, 1992), (91, 1991), (90, 1990), (89, 1989), (88, 1988), (87, 1987), (86, 1986), (85, 1985)], verbose_name='Passing Year')),
                ('total_marks', models.PositiveSmallIntegerField()),
                ('obtained_marks', models.PositiveSmallIntegerField()),
                ('division', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], verbose_name='Passing Division')),
                ('exm_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Examination Month')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.courses', verbose_name='Course Name')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
