# Generated by Django 3.1.4 on 2020-12-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201224_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLCYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='clcstudent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clcyear'),
        ),
    ]
