# Generated by Django 3.1.4 on 2020-12-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201230_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='clcstudent',
            name='fee_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal Fee'), (2, 'Tatkal Fee')], default=1),
            preserve_default=False,
        ),
    ]
