# Generated by Django 3.1.4 on 2021-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210130_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='inter_marks',
            field=models.CharField(max_length=255, null=True, verbose_name='12th Marksheet No'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='inter_roll_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="12'th Roll Code"),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='inter_roll_no',
            field=models.CharField(max_length=255, null=True, verbose_name="12'th Roll No"),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='last_session',
            field=models.CharField(choices=[('1', '2020-2022'), ('2', '2020-2023')], max_length=9),
        ),
    ]
