# Generated by Django 3.1.4 on 2021-01-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210130_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='enroll_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.session'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='hons_paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subject'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='last_session',
            field=models.CharField(choices=[('1', '2020-2022'), ('2', '2020-2023')], max_length=9, null=True),
        ),
    ]
