# Generated by Django 3.1.4 on 2021-01-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210130_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Vocational UG'), (2, 'Vocational PG'), (3, 'General PG')], default=1),
        ),
    ]
