# Generated by Django 3.1.4 on 2021-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_courses_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='composition',
            name='Subject already exist in with this course',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Subject Name'),
        ),
        migrations.AddConstraint(
            model_name='composition',
            constraint=models.UniqueConstraint(fields=('course', 'sub'), name='Subject already exist in this Composition'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='Subject already exist in with this course'),
        ),
    ]
